### ISSUE TITLE
ESP32 Guidance

### ISSUE THREAD

**Issue by phurth** [k3vmcd/ha-micro-air-easytouch#14]
@chadroad Hope you don't mind, I moved this convo to a new issue.

It looks from your description like you are trying to directly flash the Arduino IDE. I think you're trying to do something that's not necessary. If your goal is to flash with ESPHome for use with Home Assistant, you should be following the instructions here:

https://esphome.io/guides/getting_started_hassio

**Comment by chadroad** [comment]
No problem. Sorry man, and thanks!

**Comment by chadroad** [comment]
So I finally got my ESP32 connected inside HA. I was missing the https connection part. But now that it's setup and working, connected to wifi, how am I supposed to get it working or connected to the Micro-Air EasyTouch?

Sorry, I am new to ESP32.

**Comment by k3vmcd** [comment]
Nice!

Before you start, it's probably best to remove any EasyTouch device you currently have set up so you can start fresh. Plus make sure you have this integration still installed via HACS (either v0.1.10, v0.1.11-alpha, or v0.2.0-alpha-2).

1. Go to your ESPHome Builder tab

<img width="264" alt="Image" src="https://github.com/user-attachments/assets/19693c33-1f68-4c70-9132-4aacece8af5b" />

2. Edit your current ESP configuration

![Image](https://github.com/user-attachments/assets/f1e62d02-d281-447e-81a7-a08d266f6bbb)

3. **COPY** your current working configuration to a text file (Mac: Text Edit / Windows: Notepad) so you have the values for the next step & you don't lose it in case you need to retrace your steps (Select-All, Copy, Paste to text file... Either save to a secure location or delete when you're done because it has your ESP communication encryption keys in it).

4. Copy and paste this yaml configuration text into the ESP Home Builder window.
```
esphome:
  name: <device_name>
  friendly_name: <Device Friendly Name>

esp32:
  board: esp32-s3-devkitc-1 # Change to your board
  flash_size: 4MB # Optional
  framework:
    type: esp-idf
    #version: 5.1.2
    #platform_version: 6.5.0

# Enable logging
logger:
  level: VERBOSE
  logs:
    esp32_ble_tracker: ERROR

# Enable Home Assistant API
api:
  encryption:
    key: <"generated_encryption_key">

ota:
  platform: esphome
  password: <"generated_ota_password">

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: <'Device-Friendly-Name-Proxy'>
    password: <'generated_ap_password'>

captive_portal:

# Bluetooth Proxy
bluetooth_proxy:
  active: True

esp32_ble_tracker:
  ### Improve Bluetooth Proxy Performance per https://esphome.io/components/bluetooth_proxy#improving-reception-performance ###
  scan_parameters:
    interval: 1100ms
    window: 1100ms
  ### Improve Bluetooth Proxy Performance ###

  # Restart button
button:
  - platform: restart
    name: <"Friendly Button Name Restart">
```

5. Replace all of the places I have placeholders between the angle brackets `<` and `>` with *your saved text file values*. Also insert your specific `board:` value if it differs from mine.
**NOTE**: You must have USB-flashed your device to `esp-idf` framework type. This differs from the standard arduino installation outined in the ESPHome documentation, and you cannot wirelessly change it from arduino to esp-idf.

6. Click the "Save" button. Click the "Install" button. Click "Wirelessly" (unless you choose to do it differently). Watch the code compile for about 10-15 min and leave the window open so it doesn't get interrupted. Once you see the green "SUCCESS", then you should see an upload percentage tracker as it flashes the device. Then wait as the device reboots and then you should see the logs start scrolling past really quickly as it begins proxying all nearby bluetooth traffic to Home Assistant.

Note: If it fails to compile, try to make sure you're on Home Assistant Core 2025.3.0 and ESPHome 2025.2.2. I just got a successful compile with these versions using the default esp-idf framework. Some boards may be better, but my board often has issues compiling, usually due to a missing dependency package, which I'm pretty sure is related to whatever build tools version is included in the latest HA Core and ESPHome. If you are really struggling to get it to compile, try to uncomment where I have `version: 5.1.2` and `platform_version: 6.5.0` as those are about 1yr-old versions of the esp-idf framework that was working for me for awhile.

7. Now that you have a working bluetooth proxy and you have set it to `active: True`, in Home Assistant you probably already have a notification that it found your EasyTouch (and probably several other devices), which you can just click and configure, or you can go to Settings -> Devices & Services -> Add Integration -> Type "Micro" and select the "Micro-Air EasyTouch Thermostat" integration and enter the configured bluetooth username and password for the device.
