### ISSUE TITLE
0.10.0 Discovers thermostats, sensors unavailable

### ISSUE THREAD

**Issue by phurth** [k3vmcd/ha-micro-air-easytouch#3]
Hi! First, thank you for making this progress on the integration! Awesome work.

I installed the custom repository in HACS, rebooted, and both on my thermostats were auto discovered. I have 2 rigs, both with Easy Touch thermostats. One connects fine (the one in the same rig as HA) and the other times out, but that's just a range issue.

The main concern is that the thermo to which I am able to connect shows fine in HA devices but all sensors show as unavailable. I don't see any relevant log entries.

![Image](https://github.com/user-attachments/assets/cafd3f12-3499-44d6-9999-4209cb8aabe6)
![Image](https://github.com/user-attachments/assets/2a1d2196-44db-4b9a-b45d-6d31b0dd9468)

**Comment by phurth** [comment]
I should note the environment: For the thermostat above, Home Assistant is running in a Docker container and bluetooth connectivity is being provided by an ESP32 BT proxy

**Comment by k3vmcd** [comment]
Can you check your bluetooth proxy is in Active mode. For ESP bluetooth proxies you must put it in "active" mode with this in the ESPHome configuration:

```
# Bluetooth Proxy
bluetooth_proxy:
  active: True
```

**Comment by phurth** [comment]
> Can you check your bluetooth proxy is in Active mode. For ESP bluetooth proxies you must put it in "active" mode with this in the ESPHome configuration:
> 
> ```
> # Bluetooth Proxy
> bluetooth_proxy:
>   active: True
> ```

It is. The t-stat is discovered, so BT seems to be working, just no sensor data.

**Comment by phurth** [comment]
The plot thickens. Debug log:
```
2025-02-21 13:29:47.949 DEBUG (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser] Connecting to BLE device: C4:5B:BE:8A:16:5A
2025-02-21 13:29:49.164 DEBUG (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser] Authentication sent successfully
2025-02-21 13:29:49.165 DEBUG (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser] Connected and authenticated to BLE device: C4:5B:BE:8A:16:5A
2025-02-21 13:29:54.925 DEBUG (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser] Successfully polled device: {'SN': '355000406', 'autoHeat_sp': 50, 'autoCool_sp': 80, 'cool_sp': 80, 'heat_sp': 65, 'dry_sp': 72, 'u5': 45, 'fan_mode_num': 2, 'cool_mode_num': 128, 'u8': 128, 'u9': 128, 'mode_num': 0, 'heat_mode_num': 0, 'facePlateTemperature': 39, 'u13': 255, 'u14': 0, 'current_mode_num': 0, 'ALL': {'Type': 'Response', 'RT': 'Status', 'TT': 'EasyTouch', 'SN': '355000406', 'REV': '1.0.6.9', 'alertLL': 40, 'alertUL': 100, 'CI': 136, 'Z_sts': {'0': [50, 80, 80, 65, 72, 45, 2, 128, 128, 128, 0, 0, 39, 255, 0, 0], '1': [68, 72, 80, 68, 72, 45, 2, 128, 128, 128, 0, 0, 41, 255, 0, 0]}, 'PRM': [0, 3, -32768, 39], 'hA': 0}, 'current_mode': 'off', 'mode': 'off', 'fan_mode': 'manualH', 'cool_mode': 'full auto', 'heat_mode': 'off'}
2025-02-21 13:29:56.822 DEBUG (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser] Disconnected from BLE device
2025-02-21 13:29:56.822 DEBUG (MainThread) [custom_components.micro_air_easytouch] Finished fetching MicroAirEasyTouch_C4:5B:BE:8A:16:5A data in 8.873 seconds (success: True)
```

**Comment by k3vmcd** [comment]
That's an interesting one. Do you have more than one Bluetooth proxy?

**Comment by phurth** [comment]
No, just one.

**Comment by phurth** [comment]
If it helps troubleshoot, I have two RVs, each one has an EasyTouch and it's own instance of Home Assistant. The instance above (RV#1) is running on Docker and uses an ESP32 BT proxy. RV#2 has HASS OS running in a VM using the built-in BT adapter on the host, not a proxy.

Both instances are failing setup after successful device discovery. They are different errors though (because of course they are :) ).

RV#1: Failed setup, will retry: Bluetooth GATT Error address=C4:5B:BE:8A:16:5A handle=42 error=133 description=Error
RV#2: Failed setup, will retry: [org.bluez.Error.Failed] Operation failed with ATT error: 0x0e (Unlikely Error)

This is with 0.1.2 (I think... I've redownloaded the HACS component, which is 0.1.2, but the integrations reports that it is 0.1.1).

**Comment by k3vmcd** [comment]
maybe I'm sending commands too quickly for your adapter on RV#2 per this https://github.com/hbldh/bleak/issues/1075

**Comment by phurth** [comment]
Tried upgrading both RVs to 0.1.4. Now there are no errors in the UI for the integration, but also no data - sensors are all still unavailable.

Here's a debug log from RV#1:
`2025-02-23 10:33:31.189 DEBUG (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser] Authentication sent successfully
2025-02-23 10:33:31.190 DEBUG (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser] Authentication successful on attempt 1/3
2025-02-23 10:33:31.190 DEBUG (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser] Connected and authenticated to BLE device: C4:5B:BE:8A:16:5A
2025-02-23 10:33:31.741 ERROR (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser] Bluetooth error connecting to device: Bluetooth GATT Error address=C4:5B:BE:8A:16:5A handle=42 error=133 description=Error
2025-02-23 10:33:31.762 DEBUG (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser] Disconnected from BLE device
2025-02-23 10:33:31.762 DEBUG (MainThread) [custom_components.micro_air_easytouch] Poll completed successfully: SensorUpdate(title=None, devices={}, entity_descriptions={}, entity_values={}, binary_entity_descriptions={}, binary_entity_values={}, events={})
2025-02-23 10:33:33.716 DEBUG (MainThread) [custom_components.micro_air_easytouch] Starting coordinator for C4:5B:BE:8A:16:5A
2025-02-23 10:33:33.716 DEBUG (MainThread) [custom_components.micro_air_easytouch.sensor] Setting entity name for face_plate_temperature: Faceplate Temperature
2025-02-23 10:33:33.716 DEBUG (MainThread) [custom_components.micro_air_easytouch.sensor] Setting entity name for mode: Mode
2025-02-23 10:33:33.716 DEBUG (MainThread) [custom_components.micro_air_easytouch.sensor] Setting entity name for current_mode: Current Mode
2025-02-23 10:33:33.716 DEBUG (MainThread) [custom_components.micro_air_easytouch.sensor] Setting entity name for fan_mode: Fan Mode
2025-02-23 10:33:33.716 DEBUG (MainThread) [custom_components.micro_air_easytouch.sensor] Setting entity name for autoHeat_sp: Auto Heat Setpoint
2025-02-23 10:33:33.716 DEBUG (MainThread) [custom_components.micro_air_easytouch.sensor] Setting entity name for autoCool_sp: Auto Cool Setpoint
2025-02-23 10:33:33.716 DEBUG (MainThread) [custom_components.micro_air_easytouch.sensor] Setting entity name for cool_sp: Cool Setpoint
2025-02-23 10:33:33.716 DEBUG (MainThread) [custom_components.micro_air_easytouch.sensor] Setting entity name for heat_sp: Heat Setpoint
2025-02-23 10:33:33.717 DEBUG (MainThread) [custom_components.micro_air_easytouch.sensor] Setting entity name for dry_sp: Dry Setpoint
2025-02-23 10:33:33.737 DEBUG (MainThread) [custom_components.micro_air_easytouch] Starting coordinator update for C4:5B:BE:8A:16:5A
2025-02-23 10:33:33.738 DEBUG (MainThread) [custom_components.micro_air_easytouch] Found BLE device, initiating poll
2025-02-23 10:33:33.738 DEBUG (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser] Connecting to BLE device: C4:5B:BE:8A:16:5A
2025-02-23 10:33:39.381 DEBUG (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser] Connection established, client connected: True
2025-02-23 10:33:39.381 DEBUG (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser] Device address: C4:5B:BE:8A:16:5A
2025-02-23 10:33:39.381 DEBUG (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser] Device details: {'source': 'EC:62:60:A2:64:08', 'address_type': 0}
2025-02-23 10:33:39.381 DEBUG (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser] Starting service discovery...
2025-02-23 10:33:39.381 DEBUG (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser] Service found: 00001801-0000-1000-8000-00805f9b34fb
2025-02-23 10:33:39.381 DEBUG (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser]   Characteristic: 00002a05-0000-1000-8000-00805f9b34fb
2025-02-23 10:33:39.381 DEBUG (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser] Service found: 00001800-0000-1000-8000-00805f9b34fb
2025-02-23 10:33:39.381 DEBUG (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser]   Characteristic: 00002a00-0000-1000-8000-00805f9b34fb
2025-02-23 10:33:39.381 DEBUG (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser]   Characteristic: 00002a01-0000-1000-8000-00805f9b34fb
2025-02-23 10:33:39.381 DEBUG (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser]   Characteristic: 00002aa6-0000-1000-8000-00805f9b34fb
2025-02-23 10:33:39.382 DEBUG (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser] Service found: 000000ff-0000-1000-8000-00805f9b34fb
2025-02-23 10:33:39.382 DEBUG (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser]   Characteristic: 0000ee01-0000-1000-8000-00805f9b34fb
2025-02-23 10:33:39.382 DEBUG (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser]   Characteristic: 0000ff01-0000-1000-8000-00805f9b34fb
2025-02-23 10:33:39.382 DEBUG (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser]   Characteristic: 0000dd01-0000-1000-8000-00805f9b34fb
2025-02-23 10:33:41.054 ERROR (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser] Authentication failed: Peripheral C4:5B:BE:8A:16:5A changed connection status while waiting for BluetoothGATTWriteResponse, BluetoothGATTErrorResponse: Unknown error (0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/bleak_esphome/backend/client.py", line 77, in _async_wrap_bluetooth_operation
    return await func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/bleak_esphome/backend/client.py", line 599, in write_gatt_char
    await self._client.bluetooth_gatt_write(
        self._address_as_int, characteristic.handle, bytes(data), response
    )
  File "/usr/local/lib/python3.13/site-packages/aioesphomeapi/client.py", line 839, in bluetooth_gatt_write
    await self._bluetooth_gatt_write(
    ...<5 lines>...
    )
  File "/usr/local/lib/python3.13/site-packages/aioesphomeapi/client.py", line 877, in _bluetooth_gatt_write
    await self._send_bluetooth_message_await_response(
    ...<5 lines>...
    )
  File "/usr/local/lib/python3.13/site-packages/aioesphomeapi/client.py", line 486, in _send_bluetooth_message_await_response
    self._raise_for_ble_connection_change(address, resp, msg_types)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aioesphomeapi/client.py", line 723, in _raise_for_ble_connection_change
    raise BluetoothConnectionDroppedError(
    ...<3 lines>...
    )
aioesphomeapi.core.BluetoothConnectionDroppedError: Peripheral C4:5B:BE:8A:16:5A changed connection status while waiting for BluetoothGATTWriteResponse, BluetoothGATTErrorResponse: Unknown error (0)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/micro_air_easytouch/micro_air_easytouch/parser.py", line 216, in authenticate
    await self._client.write_gatt_char(
    ...<3 lines>...
    )
  File "/usr/local/lib/python3.13/site-packages/bleak/__init__.py", line 786, in write_gatt_char
    await self._backend.write_gatt_char(characteristic, data, response)
  File "/usr/local/lib/python3.13/site-packages/bleak_esphome/backend/client.py", line 87, in _async_wrap_bluetooth_operation
    raise BleakError(str(ex)) from ex
bleak.exc.BleakError: Peripheral C4:5B:BE:8A:16:5A changed connection status while waiting for BluetoothGATTWriteResponse, BluetoothGATTErrorResponse: Unknown error (0)
2025-02-23 10:33:41.061 DEBUG (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser] Authentication returned False on attempt 1/3
2025-02-23 10:33:41.061 DEBUG (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser] Waiting 1 second(s) before retry
2025-02-23 10:33:42.061 WARNING (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser] Client not connected - attempting to wait for connection to be made
2025-02-23 10:33:43.063 ERROR (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser] Client not connected
2025-02-23 10:33:43.063 DEBUG (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser] Authentication returned False on attempt 2/3
2025-02-23 10:33:43.063 DEBUG (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser] Waiting 1 second(s) before retry
2025-02-23 10:33:44.064 WARNING (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser] Client not connected - attempting to wait for connection to be made
2025-02-23 10:33:45.064 ERROR (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser] Client not connected
2025-02-23 10:33:45.064 DEBUG (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser] Authentication returned False on attempt 3/3
2025-02-23 10:33:45.065 ERROR (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser] Authentication failed after 3 attempts with no exception
2025-02-23 10:33:45.065 ERROR (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser] Failed to authenticate with device
2025-02-23 10:33:45.065 DEBUG (MainThread) [custom_components.micro_air_easytouch.micro_air_easytouch.parser] Disconnected from BLE device
2025-02-23 10:33:45.065 DEBUG (MainThread) [custom_components.micro_air_easytouch] Poll completed successfully: SensorUpdate(title=None, devices={}, entity_descriptions={}, entity_values={}, binary_entity_descriptions={}, binary_entity_values={}, events={})
2025-02-23 10:33:45.065 DEBUG (MainThread) [custom_components.micro_air_easytouch] Finished fetching MicroAirEasyTouch_C4:5B:BE:8A:16:5A data in 11.327 seconds (success: True)
`

**Comment by k3vmcd** [comment]
Are you using the 'arduino' or the 'esp-idf' framework on your ESPHome device? What is your current configuration file (make sure to redact sensitive info)? If you're on arduino it tends to have issues keeping up (note that switching to esp-idf needs a wired connection to flash). If you do edit your config and it works, will you please let me know so I can document it as a requirement in the README?

https://esphome.io/components/bluetooth_proxy.html outlines specific performance improvements. Here is my configuration file for my ESPHome:

```
esphome:
  name: <device_name>
  friendly_name: <Device Friendly Name>

esp32:
  board: esp32-s3-devkitc-1 # Change to your board
  flash_size: 4MB # Optional
  framework:
    type: esp-idf
    #version: 5.1.2
    #platform_version: 6.5.0

# Enable logging
logger:
  level: VERBOSE
  logs:
    esp32_ble_tracker: ERROR

# Enable Home Assistant API
api:
  encryption:
    key: <"generated_encryption_key">

ota:
  platform: esphome
  password: <"generated_ota_password">

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: <'Device-Friendly-Name-Proxy'>
    password: <'generated_ap_password'>

captive_portal:

# Bluetooth Proxy
bluetooth_proxy:
  active: True

esp32_ble_tracker:
  ### Improve Bluetooth Proxy Performance per https://esphome.io/components/bluetooth_proxy#improving-reception-performance ###
  scan_parameters:
    interval: 1100ms
    window: 1100ms
  ### Improve Bluetooth Proxy Performance ###

  # Restart button
button:
  - platform: restart
    name: <"Friendly Button Name Restart">
```

**Comment by k3vmcd** [comment]
0.1.5 attempts to better handle a connection drop like you had in your logs.

**Comment by phurth** [comment]
I'm using esp-idf (the recommended framework for BT proxy and BTLE tracker). I am running other components on the ESP32 (Mopeka propane and Victron smartshunt sensors).

Config:

```
esphome:
  name: "mopeka-victron"
esp32:
  board: nodemcu-32s
  framework:
    type: esp-idf
esp32_ble_tracker:
    scan_parameters:
      interval: 1100ms
      window: 1100ms
      active: true
bluetooth_proxy:
   active: true
external_components:
  - source: github://Fabian-Schmidt/esphome-victron_ble
sensor:
  - platform: mopeka_pro_check
    mac_address: ""
    tank_type: 30LB_V
    temperature:
        name: "Driver Side Tank temp"
    level:
        name: "Driver Side Tank level"
    distance:
        name: "Driver Side Tank distance"
    battery_level:
        name: "Driver Side Tank battery level"
  - platform: mopeka_pro_check
    mac_address: ""
    tank_type: 30LB_V
    temperature:
        name: "Passenger Side Tank temp"
    level:
        name: "Passenger Side Tank level"
    distance:
        name: "Passenger Side Tank distance"
    battery_level:
        name: "Passenger Side Tank battery level"
  - platform: victron_ble
    victron_ble_id: rockwood_shunt
    name: "Battery voltage"
    type: BATTERY_VOLTAGE
  - platform: victron_ble
    victron_ble_id: rockwood_shunt
    name: "Time remaining"
    type: TIME_TO_GO
  - platform: victron_ble
    victron_ble_id: rockwood_shunt
    name: "Temperature"
    type: TEMPERATURE
  - platform: victron_ble
    victron_ble_id: rockwood_shunt
    name: "Current"
    type: BATTERY_CURRENT
  - platform: victron_ble
    victron_ble_id: rockwood_shunt
    name: "Consumed Ah"
    type: CONSUMED_AH
  - platform: victron_ble
    victron_ble_id: rockwood_shunt
    name: "State of charge"
    type: STATE_OF_CHARGE
  - platform: victron_ble
    victron_ble_id: rockwood_shunt
    name: "Power"
    type: BATTERY_POWER
victron_ble:
  - id: rockwood_shunt
    mac_address: ""
    bindkey: ""
button:
  - platform: restart
    name: "Restart Device"
api:
ota:
  - platform: esphome
    password: ""
wifi:
  ssid: ""
  password: ""
  manual_ip:
     static_ip: 192.168.50.42
     gateway: 192.168.50.1
     subnet: 255.255.255.0
     dns1: 192.168.50.1
logger:
  level: DEBUG
```
